# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: duolingo
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
